name: Rested.Mongo CD

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '**/*.md'
      - '.github/**'

jobs:
  build:
    name: Rested.Mongo CD
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{matrix.dotnet-version}}
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{github.token}}
    - name: Restore (Rested.Mongo)
      run: dotnet restore Rested.Mongo
    - name: Restore (Rested.Mongo.MSTest)
      run: dotnet restore Rested.Mongo.MSTest
    - name: Restore (Rested.Mongo.UnitTest)
      run: dotnet restore Rested.Mongo.UnitTest
    - name: Build (Rested.Mongo)
      run: dotnet build Rested.Mongo --configuration Release --no-restore
    - name: Build (Rested.Mongo.MSTest)
      run: dotnet build Rested.Mongo.MSTest --configuration Release --no-restore
    - name: Build (Rested.Mongo.UnitTest)
      run: dotnet build Rested.Mongo.UnitTest --configuration Release --no-restore
    - name: Test (Rested.Mongo)
      run: dotnet test Rested.Mongo --no-restore --verbosity normal
    - name: Create NuGet Package (Rested.Mongo)
      run: dotnet pack Rested.Mongo --configuration Release --no-restore --version-suffix ${{github.run_number}}
    - name: Create NuGet Package (Rested.Mongo.MSTest)
      run: dotnet pack Rested.Mongo.MSTest --configuration Release --no-restore --version-suffix ${{github.run_number}}
    - name: Publish NuGet package to GitHub Package Repository (Rested.Mongo)
      run: dotnet nuget push ./Rested.Mongo/bin/Release/*.nupkg
    - name: Publish NuGet package to GitHub Package Repository (Rested.Mongo.MSTest)
      run: dotnet nuget push ./Rested.Mongo.MSTest/bin/Release/*.nupkg